cogs/listeners/message_updates.py

Added `stearncormuntity.ru` to the auto ban list following reports.

Add a scam link to the auto-ban list.

---

cogs/tasks/reddit.py

This PR adds proper handling for missing variables and stops the background task from starting if any necessary environment variables or settings stored in the database are missing.

Revamped the Reddit background task initialization

---

cogs/commands/moderation/mutes.py

- Added a check to iterate for the staff/trial mod roles only on members that are still in the server.

Fixed a bug where autoban would break for left muters

---

cogs/listeners/member_updates.py

And some unused imports removal.

Removed config import since it's no longer exists

---

cogs/commands/moderation/administration.py
cogs/listeners/bans_handle.py

Allows manual bans to be added to mod_logs table in the database.

Bans handle

---

cogs/commands/reminder.py
cogs/tasks/reminders.py

- Fixed a bug that would make reminders occasionally fail to send due to nested exception handling.
- Reworked the logic.
- Removed the ban permission requirement for /remindme.

Remindme bug fix

---

cogs/commands/moderation/mutes.py
cogs/commands/moderation/tickets.py

- It throws an index out of bound exception due to the poorly handled time tag display algorithm while parsing into privatebin.

Fixed a bug where /unmute would break if called in a mute channel

---

cogs/commands/moderation/tickets.py

Fixed a bug where ticket topic exceeding 1024 characters would fail to create and break the bot.

Ticket bug fix

---

cogs/commands/moderation/tickets.py

- Reduced 4 API calls required for ticket channel creation to 1 API call.
- Channel topic is now set as ticket topic to avoid querying database for it.
- Removed unnecessary comments.
- Shortened comments where possible to meet PEP8.
- Improved readability on multi-line parameters where possible.

Optimized ticket channel creation, improved reliability, misc. fixes

---

chiya.py
cogs/commands/moderation/administration.py
cogs/commands/moderation/bans.py
cogs/commands/moderation/kicks.py
cogs/commands/moderation/mutes.py
cogs/commands/moderation/notes.py
cogs/commands/moderation/restricts.py
cogs/commands/moderation/tickets.py
cogs/commands/moderation/warns.py
cogs/commands/reminder.py
cogs/commands/settings.py
cogs/listeners/bans_handle.py
cogs/listeners/guild_updates.py
cogs/listeners/mutes_handle.py
cogs/listeners/restricts_handle.py
cogs/tasks/reminders.py
cogs/tasks/timed_mod_actions.py
utils/database.py
utils/embeds.py

Started fixing various unused pieces of code and imports as suggested by:
https://lgtm.com/projects/g/ranimepiracy/chiya/?mode=list

LGTM optimizations

---

Dockerfile
README.md
cogs/commands/general.py
cogs/commands/moderation/mutes.py
cogs/commands/moderation/tickets.py
cogs/commands/reminder.py
cogs/tasks/reddit.py
config.default.yml
docker-compose.dev.yml
docker-compose.yml
requirements.txt
utils/config.py
utils/database.py

This PR attempts to fix some of the issues with the original v1 migration of the settings to config.yml which worked on bare metal environments but failed in Docker environments.
- Switched from pyyaml to pyaml_env for environment variable handling
- Migrated config loading from pyyaml to pyyaml_env and simplified logic
- Migrated the config.default.yml to the new environment variables
- Removed deprecated volume declarations in the Dockerfile
- Database name is automatically defaulted to chiya now
- Added docker-compose for compiling from local source code 
- Removed some bloat from the top of the requirements.txt file because the link explains what the file is and the command provided will not work on all systems
- Removed unused LOG_LEVEL environment variable from the docker-compose …

Settings yaml migration v2

---

cogs/listeners/autoresponders.py

Autoresponder would only respond to lowercase invocation, and this PR aims to fix that by making it case insensitive.

Fixed autoresponder being case sensitive.

---

chiya/cogs/commands/mute.py

just trying out github pls no bulli

Fixed mute description saying kicked instead of muted

---

chiya/utils/helpers.py

Fixes a bug in the mod action checker which allowed mods to action other mods.

Fix mods being able to action other mods.

---

chiya/cogs/listeners/mute.py

Adds a listener that automatically adds manual timeouts to the mod log.

Add manual timeouts to mod log.

---

chiya/utils/helpers.py

Based on [https://github.com/Snaacky/chiya/pull/129](#129) except that years and months were excluded because the timedelta() method doesn't support such kwargs.

Added week support to reminder

---

.github/workflows/docker-publish.yml

- Also bumped to use checkout v3

Now uses ghcr.io

---

chiya/cogs/commands/mute.py
chiya/cogs/commands/reminder.py
chiya/utils/helpers.py

Also made some algorithm simplifications.

Added month and year support

---

chiya/cogs/listeners/starboard.py

This hopefully fixes a race condition issue where duplicated embeds are sent if multiple stars were reacted on a message very quickly after it hit the star threshold, caused by the code unable to add the IDs into the database in time.

Implemented starboard cache

---

Dockerfile
config.default.yml
docker-compose.yml

- Separated ENV and RUN commands in the Dockerfile into single lines for improved readability.
- Tweaked some of the comments in the Dockerfile.
- docker-compose.yml now uses hardcoded paths rather than environment variables because it was adding unnecessary bloat.
- Moved the PYTHONPATH environment variable into the Dockerfile rather than keep it in the docker-compose file.

Improved Dockerfile and docker-compose.yml

---

chiya/cogs/listeners/starboard.py

Show all stickers and attach as image if the only image.

Support stickers in starboard embed

---

chiya/cogs/apps/move_question.py

- Now support attachments.
- Fixed a bug that throws 400 unknown message due to the message object being accessed after it was deleted.

Move question fix

---

chiya/cogs/listeners/starboard.py

- Fixed the cache preventing race condition was not properly working.
- Added the cache implementation to reaction remove event to prevent the unknown message error if stars are removed to below the threshold too quickly.

Starboard cache optimization

---

chiya/cogs/commands/general.py

- Simplify the logic
- Change to use display_avatar.url instead of display_avatar

Change PFP logic and use url

---

chiya/cogs/commands/ban.py
chiya/cogs/commands/general.py
chiya/cogs/commands/mute.py
chiya/cogs/commands/note.py
chiya/cogs/commands/warn.py
chiya/cogs/listeners/ban.py
chiya/utils/helpers.py

pycord will automatically fallback from discord.Member to discord.User if the user being queried does not exist in the guild.

Updated type hints because discord.Member falls back to discord.User

---

chiya/cogs/commands/general.py

3rd party and local imports got clumped together rather than being sorted properly.

Fixed commands/general.py imports being arranged out of order

---

chiya/cogs/apps/general.py
chiya/cogs/apps/vote.py
chiya/cogs/commands/general.py

Fixes vote command by falling back to 👍 and 👎 if the emotes are not present.

Fix Vote command

---

chiya/cogs/commands/trackerstatus.py
chiya/utils/trackerstatus.py

- Move them to classes based on an interface
- Support for AB and MAM

Improved new implementation of TrackerStatus

---

chiya/cogs/listeners/starboard.py

- Shifted the logic flow of when to close the database connection to be more in line with other similar ones.
- Embed footer's message ID is casted to string to match the expected parameter data type.
- Removed unnecesary return at the end of the execution block.

Optimized starboard logic

---

Dockerfile
chiya/database.py

- Emojis will now work properly in mod actions reasons.
- Removed .setup() from __init__ because it was being manually called anyways and now it's no longer being ran every time the database is called (every few seconds...).
- Added missing logs on database operations.
- Fixed PYTHONIOENCODING value in Dockerfile because it's utf-8 and not utf8.

Emojis now work in mod actions, optimized logic

---

chiya/cogs/listeners/starboard.py

- Adds more urls used by tenor
- Fix issue with replacing original embed

Resolve Starboard Tenor issues

---

chiya/cogs/commands/trackerstatus.py
chiya/utils/trackerstatus.py

- Fix bot failing to respond if the tracker didn't exist.
- Add color support
- Fix Lint errors

Trackerstatus fixes

---

pyproject.toml

Bumped dataset 1.6.0 to fix upstream library issues breaking the bot.

Bumped dataset to 1.6.0

---

chiya/cogs/commands/note.py

Move db.close after iteration of data

Fix Search error

---

chiya/cogs/commands/purge.py

fix: revert earlier commit

---

chiya/cogs/apps/report_message.py

Current Behavior: The interaction errors out if you tried to cancel a report.

fix: reports can now be cancelled

---

chiya/cogs/interactions/ticket.py

the old link is dead, i downloaded the same image on google and i uploaded it again to imgur

fix: Changed broken imgur link
