Snaacky/chiya

cogs/listeners/error_handle.py, utils/pagination.py
Replaced all occurrences of `log.trace` with `log.debug`, since the handler for trace logging doesn't seem to exist.
=> Reminder bug hotfix

cogs/commands/settings.py
The old logic was to query the entire "settings" database and copy every single data entry into a dictionary, with a "censored" key that also had no use and is extremely inefficient when being called en mass such as with on_message calls.
=> Reworked the look up logic

chiya.py, cogs/commands/moderation/bans.py, cogs/commands/moderation/kicks.py, cogs/commands/moderation/mutes.py, cogs/commands/moderation/notes.py, cogs/commands/moderation/restricts.py, cogs/commands/moderation/tickets.py, cogs/commands/moderation/warns.py, cogs/commands/reminder.py, cogs/commands/settings.py, cogs/listeners/bans_handle.py, cogs/listeners/mutes_handle.py, cogs/listeners/restricts_handle.py, cogs/tasks/reminders.py, cogs/tasks/timed_mod_actions.py, utils/database.py
The database class previously only returned the formatted URL string and not the object itself requiring us to import dataset in any file where a database operation was occurring which was redundant. 
get_db() was renamed to get() and now returns the Dataset database object. The new url() function has the same functionality as the old get_db() which is used for creating the database if it didn't already exist.
=> Migrated database.py to class, get function now returns Database object

cogs/commands/moderation/notes.py
- Sort is now done newest to oldest so the latest mod actions will show up first for clarity.
- Moved action ID to its own line to help clean things up and for consistency.
- The timeout for the reactions was increased to 120 seconds which should be more than enough time for review.
=> Sort is now newest to oldest, moved ID now on newline, increased timeout

cogs/listeners/mutes_handle.py
Fixes a bug with mute evasion handler not banning and archiving the mute channel.
=> Mute archive command no longer has guild keyword argument.

utils/embeds.py
Due to a spelling error in the embed generation function, the application no longer displayed a success message. This PR fixes that bug.
=> Fix Moving Questions Application

cogs/commands/mutes.py, cogs/commands/tickets.py
Fixed mute and ticket channel log on privatebin can only contain up to 99 messages.
=> Mute log hotfix

chiya/cogs/commands/trackerstatus.py
Relies on trackerstatus.info for API data at the moment. 
There are plans noted in the comments under the "TODO:" for supporting trackers that offer their own status pages rather than solely relying on trackerstatus.info. There are also plans in the comments for changing the embed color based on the availability of the tracker's services.
It would be nice to also support some more features not documented in the comments like displaying the full tracker name in the title instead of just the acronym, using the embed thumbnail to display the tracker favicon, and eventually supporting tracking our own data. 
There are a few small places that could use improvement in the code:
- The `log.error(e)` could use some context in the outputted string before the `e` so it's more apparent where the …
=> Implemented /trackerstatus command

chiya/cogs/interactions/ticket.py
This PR fixes a bug where a ticket would fail to close if the ticket creating member is no longer a part of the guild.
=> Fix ticket failing to close if member leaves guild

.github/workflows/docker-publish.yml
- Fixed name so Docker images are now located under snaacky/chiya:latest instead of snaacky/chiya/chiya:latest.
- Implemented caching to hopefully speed up Docker image builds (cache is located under chiya-stages which is hidden from non-maintainers).
- Simplified bloat in docker-publish.yml because there was a lot of lines that were never used.
- Removed the "test" job which was just a Docker image build that never got pushed anywhere before the actual build occurred because it just increased total build time for no reason.
It seems like performance for this is all over the board, seems mostly out of our control, but I've seen compile times as low as 50s and some ranging around 2-4 minutes, which is a huge improvement over our previous 6-7 minute build times. We can probably tweak this …
=> docker-publish.yml now properly builds to repo

chiya/utils/embeds.py
This PR fixes a bug where the remindme command wouldn't respond to users who didn't have an avatar set.
Edit: This PR fixes almost all commands that use `embeds.make_embed()` to generate embeds, that fail due to the command invoker not having a profile picture set.
=> Fix /remindme not responding to users with no avatar set

Dockerfile
- Updated Poetry to 1.2.0b2 for `--all-extras` support. This functionality is only available in the pre-release wheel so the Dockerfile was modified to `pip install` that wheel. This will have to be reverted back to the regular installer after >=1.2.0b2 is added to the installer.
- Switched to `--all-extras` so we no longer have to manually declare what extra dependencies we need in the Dockerfile.
- `--no-dev` is deprecated in 1.2.0b2, using `--only main` now instead.
=> Poetry install now installs all extras

.github/workflows/docker-publish.yml
`github.actor` was preventing the Docker image from being pushed by anyone other than the repository owner. `github.repository_owner` works with both commits in the main repository as well as on forks.
=> Changed build username to repository owner instead of commit pusher

docker-compose.yml
Bumped to 3.7 which is the second to latest docker-compose version because Ubuntu 20.04 still does not have 3.8 supported in their package repository.
xoxo munchie
=> Bumped docker-compose version to 3.7

chiya/cogs/listeners/starboard.py
If you react to your own post and then someone else reacts as well. It will count your own as you are not person who initiated that react. This fixes that issue and well as setting the payload Class and return type.
=> Fix issue with author reacts being counted on SB

chiya/cogs/listeners/boost.py, config.default.yml
Mention the ticket channel instead of the Staff role in the boost embed.
Add Ticket channel to default config.
=> Direct booster to tickets instead of staff

chiya/utils/helpers.py
- Previously, the guild owner logic was too low so that even the owner couldn't override certain safety checks.
- Updated the self-bot check to check to see if the bot's ID matches rather than blanket disallowing all bots from being actioned.
- Added a check so that in the case of a discord.Member falling back to a discord.User, the bot will skip the checks that are dependent on a discord.Member object.
=> Fixed bugs in can_action_member logic

chiya/cogs/commands/ban.py, chiya/cogs/commands/mute.py, chiya/cogs/commands/warn.py, chiya/cogs/interactions/ticket.py
discord.Forbidden doesn't handle every exception such as when a bot is banned, because a bot can't DM another bot, therefore we need to handle discord.HTTPException as well.
=> Added discord.HTTPException to moderation command exceptions

chiya/cogs/commands/ban.py, chiya/cogs/commands/note.py
- Removed an instance where `fetch_user()` in `commands/ban.py` was called when a user was banned.
- Removed `isinstance()` check before `fetch_user()` call because the instance check is now handled under `can_action_member`.
- Removed `fetch_user()` calls in `commands/note.py` when adding adding a note to a user's profile or when a moderator searched for a user's notes.
=> Removed fetch_user calls when the user object had already fallen back

chiya/database.py
Emotes and emojis require the collation to be set to utf8mb4_unicode_ci. This fixes issues with mods being unable to use emotes or emojis in action reasons.
=> Default all tables created by dataset to utf8mb4_unicode_ci

chiya/bot.py
The previous implementation made it so that cogs could not access any bot values during their initialization because the bot was loading the cogs before connecting to the Discord network. This fixes that going forward.
The root_dir for the cog loading was changed so that it will uses the parent directory of the executing script rather than just using a hardcoded "chiya" value which is rather unnecessarily static.
Removed the legacy comment about registering commands because this seems to be fixed in later versions of Pycord although we plan to switch to discord.py eventually anyways.
=> Moved cog loading into on_ready and made the loading more dynamic

poetry.lock, pyproject.toml
"Unfortunately, we discovered a vulnerability which lets users shut down bots remotely in certain circumstances. We've patched the issue in version 2.0.1, so please update as soon as possible. In addition, we issued CVE-2022-36024 through a GitHub security advisory."
=> Bumped pycord to 2.0.1 due to CVE-2022-36024

chiya/database.py
Previously, we were setting the collation every time the bot ran which was completely unnecessary because it should never change after the database is initially created. This check will verify the character set at the cost of a few extra queries (which should theoretically cause 0% noticeable impact) and only update the collation when necessary. Annoyingly, dataset does not expose the collation in any capacity despite it being exposed by the underlying SQLAlchemy.
=> Fixed database collation check so it doesn't run every bot start

chiya/cogs/listeners/autoresponder.py
When users sent messages to the bot over DMs, it would throw a traceback because the bot would try to run .roles on the user but seeing as they are in DMs, the message.author is a discord.User and not a discord.Member. This adds a check to prevent that bit of code from executing in the context of DMs.
=> Fixed traceback exception that would occur when users DM the bot

chiya/utils/trackerstatus.py
Previously, by just logging `e`, we were spamming console with upwards of 3-6 lines per error and it would produce a bunch of obnoxious blank newlines.
=> Adjusted tracker status error log level and message

chiya/cogs/commands/administration.py, chiya/cogs/commands/ban.py, chiya/cogs/commands/general.py, chiya/cogs/commands/mute.py, chiya/cogs/commands/note.py, chiya/cogs/commands/purge.py, chiya/cogs/commands/reminder.py, chiya/cogs/commands/server.py, chiya/cogs/commands/trackerstatus.py, chiya/cogs/commands/warn.py, chiya/cogs/listeners/autoresponder.py, chiya/cogs/tasks/reminder.py, chiya/utils/helpers.py
- Mod actions are now ephemeral and action embeds are logged to a channel.
- Reminders are now ephemeral, no longer attempt to send in the channel they were invoked in, and just send to the user's DMs instead. The user is warned when they create the reminder that they need to keep their DMs open.
- Finally got around to cleaning up the admin cog.
- Various comment and docstring cleanups across the codebase.
- Separated embeds that the user receives and embeds that the moderator receives into `user_embed` and `mod_embed` across the codebase for clarity and consistency.
- Made various helper functions that didn't need to be async into sync functions.
- Cleaned up function names and excessively verbose code where possible.
- Removed descriptions from command groups because they often cause …
=> Mod actions are now ephemeral and logged to a channel, misc. changes 

chiya/cogs/commands/purge.py
Current Behavior: Purge skips the last message sent in a channel.
=> fix: Purge now includes last message sent

chiya/cogs/apps/report_message.py
the close report doesn't work after restarting the bot
and moving the code in to inside the cog class fixed it
=> fix: close report button not working after the bot restart
